# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 15:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('main', '0002_auto_20160901_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Found',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, default=None, null=True, upload_to='/static/user_upload_img')),
                ('detail', models.CharField(blank=True, max_length=256)),
                ('phone', models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator(code='Invalid phone number', message='手机号码不合法', regex='1\\d{10}')])),
                ('email', models.EmailField(blank=True, max_length=128)),
                ('remark', models.CharField(blank=True, max_length=256)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('paired', models.BooleanField(default=False)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Category')),
                ('lfoffice', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.LFOffice')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.UserExt')),
            ],
        ),
    ]
