# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import found.models


class Migration(migrations.Migration):

    dependencies = [
        ('found', '0002_auto_20160905_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='found',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=found.models.get_file_path),
        ),
    ]
