# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160901_2338'),
        ('found', '0003_auto_20160906_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='found',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Location'),
        ),
    ]
