# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 08:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('found', '0005_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='found',
            name='phone',
            field=models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator(code='Invalid phone number', message='手机号码不合法', regex='1\\d{10}')]),
        ),
    ]
