# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-23 07:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_auto_20160901_2338'),
        ('user', '0006_auto_20160917_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(default='-1', max_length=32)),
                ('name', models.CharField(default='error', max_length=128)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('paired', models.BooleanField(default=False)),
                ('location', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Location')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.UserExt')),
            ],
        ),
    ]
