# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-23 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160901_2338'),
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='location',
        ),
        migrations.AddField(
            model_name='card',
            name='lfoffice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.LFOffice'),
        ),
    ]
