# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-31 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_auto_20161023_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='lfoffice',
            field=models.CharField(default='error', max_length=128),
        ),
    ]
