# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 15:02
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Found',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, default=None, null=True, upload_to='/static/user_upload_img')),
                ('detail', models.CharField(blank=True, max_length=256)),
                ('phone', models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator(code='Invalid phone number', message='手机号码不合法', regex='1\\d{10}')])),
                ('email', models.EmailField(blank=True, max_length=128)),
                ('remark', models.CharField(blank=True, max_length=256)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('paired', models.BooleanField(default=False)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Category')),
            ],
        ),
        migrations.CreateModel(
            name='LFOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('detail', models.CharField(blank=True, max_length=256)),
                ('contact', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_type', models.SmallIntegerField(choices=[(0, 'superuser'), (1, 'staff'), (2, 'user')])),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(max_length=150)),
                ('operation_type', models.SmallIntegerField(choices=[(0, 'ADD'), (1, 'EDIT'), (2, 'DELETE'), (3, 'PAIR')])),
                ('object_type', models.SmallIntegerField(choices=[(0, 'User'), (1, 'Category'), (2, 'LFOffice'), (3, 'Location'), (4, 'Lost'), (5, 'Found')])),
                ('object_id', models.IntegerField()),
                ('detail', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Lost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, default=None, null=True, upload_to='/static/user_upload_img')),
                ('detail', models.CharField(blank=True, max_length=256)),
                ('phone', models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator(code='Invalid phone number', message='手机号码不合法', regex='1\\d{10}')])),
                ('email', models.EmailField(blank=True, max_length=128)),
                ('remark', models.CharField(blank=True, max_length=256)),
                ('thank', models.SmallIntegerField(choices=[(0, '未选择答谢'), (1, '答谢')])),
                ('thankDetail', models.CharField(blank=True, max_length=128)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('paired', models.BooleanField(default=False)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Category')),
                ('location', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Location')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserExt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=128, unique=True)),
                ('jaccount', models.CharField(blank=True, max_length=256, unique=True)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('gender', models.SmallIntegerField(blank=True, choices=[(0, '未知'), (1, '男'), (2, '女'), (3, '其他')])),
                ('email', models.CharField(blank=True, max_length=128, unique=True)),
                ('phone', models.CharField(blank=True, max_length=32, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid phone number', message='手机号码不合法', regex='1\\d{10}')])),
                ('type', models.SmallIntegerField(blank=True, choices=[(0, '未知'), (1, '本科生'), (2, '研究生'), (3, '博士生'), (4, '教职工')])),
                ('score', models.IntegerField(default=0)),
                ('money', models.IntegerField(default=0)),
                ('wechat', models.CharField(blank=True, max_length=256, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='found',
            name='lfoffice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.LFOffice'),
        ),
        migrations.AddField(
            model_name='found',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
