# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 08:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Volunteers',
            new_name='Volunteer',
        ),
    ]
