# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_lostitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostitem',
            name='STATUS',
            field=models.IntegerField(default=0),
        ),
    ]
