# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20160929_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostitem',
            name='img',
            field=models.FileField(default=django.utils.timezone.now, upload_to='/media/lost/'),
            preserve_default=False,
        ),
    ]
