# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-07 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_lostitem_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitem',
            name='img',
            field=models.FileField(upload_to='./lost/'),
        ),
    ]
