# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0003_lost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lost',
        ),
    ]
