# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 15:41
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=128, unique=True)),
                ('jaccount', models.CharField(blank=True, max_length=256, unique=True)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('gender', models.SmallIntegerField(blank=True, choices=[(0, '未知'), (1, '男'), (2, '女'), (3, '其他')])),
                ('email', models.CharField(blank=True, max_length=128, unique=True)),
                ('phone', models.CharField(blank=True, max_length=32, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid phone number', message='手机号码不合法', regex='1\\d{10}')])),
                ('type', models.SmallIntegerField(blank=True, choices=[(0, '未知'), (1, '本科生'), (2, '研究生'), (3, '博士生'), (4, '教职工')])),
                ('score', models.IntegerField(default=0)),
                ('money', models.IntegerField(default=0)),
                ('wechat', models.CharField(blank=True, max_length=256, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
