# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userext',
            name='type',
            field=models.SmallIntegerField(choices=[(0, '未知'), (1, '本科生'), (2, '研究生'), (3, '博士生'), (4, '教职工')], default=0),
        ),
    ]
