# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 11:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20160906_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userext',
            name='email',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userext',
            name='jaccount',
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userext',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userext',
            name='phone',
            field=models.CharField(max_length=32, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid phone number', message='手机号码不合法', regex='1\\d{10}')]),
        ),
    ]
