# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-17 06:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userext',
            name='gender',
            field=models.SmallIntegerField(blank=True, choices=[(0, '未知'), (1, '男'), (2, '女'), (3, '其他')]),
        ),
        migrations.AlterField(
            model_name='userext',
            name='phone',
            field=models.CharField(max_length=32, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid phone number', message='手机号码不合法', regex='1\\d{10}')]),
        ),
        migrations.AlterField(
            model_name='userext',
            name='type',
            field=models.SmallIntegerField(choices=[(0, '未知'), (1, '本科生'), (2, '研究生'), (3, '博士生'), (4, '教职工')], default=0),
        ),
    ]
