# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lost',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='lost'),
        ),
    ]
