# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 08:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0004_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lost',
            name='phone',
            field=models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator(code='Invalid phone number', message='手机号码不合法', regex='1\\d{10}')]),
        ),
        migrations.AlterField(
            model_name='lost',
            name='thank',
            field=models.SmallIntegerField(choices=[(0, '未选择答谢'), (1, '答谢')]),
        ),
    ]
